### ISSUE TITLE
Excel-Datei

### ISSUE THREAD

**Issue by CapRowo** [epoell/Wahlpflichtmanager#1]
Danke für den Wahlpflichmanager, das ist genau was ich gesucht habe und selbst nicht hinbekomme. Wäre es vielleicht möglich die Exceldatei aus dem Beispiel zur Verfügung zu stellen?

**Comment by epoell** [comment]
Hallo,

das freut mich sehr!
Ich habe die Datei gerade nicht mehr vorliegen - aber werde nächste Woche versuchen eine entsprechende Datei zu erstellen und hochzuladen. Bis dahin: Im Code sind (etwas versteckt in den Kommentaren am Anfang) auch die Namen der Tabellenblätter und die Spaltensortierung genannt.

**Comment by epoell** [comment]
Ich habe eine Excel-Datei erzeugt und hochgeladen, viel Spaß :)
